### ISSUE TITLE
Compiled Solutions

### ISSUE THREAD

**Issue by EHCanadian** [lunarmodules/luasec#151] opened 2019-12-04 16:36 UTC
Anyone have a public compiled luasocket 2.0.2+ and luasec libraries for x86 or x64 under windows 7+

**Comment by pkulchenko** [comment] 2019-12-04 16:46
I have them compiled for Lua 5.1 available here: https://download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win64.zip and https://download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win32.zip. I also have a bit newer version of openssl compiled for Lua 5.1-5.3, but only for win32 (see the content of clibs, clibs52, and clibs53 folders in this branch: https://github.com/pkulchenko/ZeroBraneStudio/tree/luasec-0.9-openssl-1.1.1d-64bit/bin).

**Comment by stefanak-michal** [comment] 2022-02-17 10:40
Please, can we get actual?

**Comment by alerque** [comment] 2024-01-06 20:25
Duplicate of #115.

**Closed by alerque** 2024-01-06 20:25 UTC
